version: '2'
services:
  consentservice:
    image: kvalitetsit/consent-service:latest
    environment:
      - DB_DRIVER=com.mysql.jdbc.Driver
      - DB_PASSWORD=consent1234
      - DB_USERNAME=consent
      - DB_URL=jdbc:mysql://mysqldb:3306/consent
      - NOTIFICATION_SERVICE_URL=http://jsontomqservice:8090/notificationservice
      - UID_KEY=urn:dk:gov:saml:cprNumberIdentification
      - USERSERVICE_URL=http://usercontext:9200
      - FLYWAY_PLACEHOLDERS_MUNICIPALITY=561
    ports:
      - "8097:80"
  consentwebgui:
    image: kvalitetsit/consent-webgui:latest
    environment:
      - CONSENTSERVICE_URL=http://consentservice
      - CONTEXT=cwg
      - SERVER_PORT=8080
    ports:
      - "8099:8080"
  consentadmingui:
    image: kvalitetsit/consent-admingui:latest
    environment:
      - CONSENTSERVICE_URL=http://consentservice
      - CONTEXT=cag
      - SERVER_PORT=8080
    ports:
      - "8100:8080"